"""Intern modules live here.

Each subdirectory is one independent module owned by one intern on one branch.
Do NOT edit this file to register modules — discovery is automatic.
See app/module_loader.py and docs/MODULE_GUIDE.md.
"""
